config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :tasks
  get 'signup', to: 'users#new'
  resources :users, except: [:new, :show, :index]
  get 'login', to: 'sessions#new', as: 'new_user_session'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories
  get 'tasks_today', to: 'tasks#today', as: 'tasks_today'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :title, presence: true, uniqueness: { scope: :user, case_sensitive: false }, length: { minimum: 3, maximum: 25 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, presence: true, length: { minimum: 4, maximum: 30 }
  validates :detail, presence: true, length: { minimum: 10, maximum: 300 }
  validates :due_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :categories, dependent: :destroy
  has_many :tasks
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
                    uniqueness: { case_sensitive: false }, 
                    length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You need to log in or sign up before continuing."
      redirect_to login_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully."
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def index
    @categories = current_user.categories
  end

  def show
    @tasks = @category.tasks
  end

  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "Category title was updated successfully."
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = current_user.categories.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to categories_path, notice: "No such category associated to the current user."
  end

  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to categories_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Signed in successfully"
      redirect_to categories_path
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Signed out successfully"
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  def show
  end

  def index
    @tasks = current_user.tasks
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:notice] = "Task was created successfully."
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      flash[:notice] = "Task was updated successfully."
      redirect_to task_path(@task)
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def today
    @tasks = current_user.tasks.where('due_date = ?', Date.current)
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id]) 
  rescue ActiveRecord::RecordNotFound
    redirect_to tasks_path, notice: "No such task associated to the current user."
  end

  def task_params
    params.require(:task).permit(:name, :detail, :due_date, :category_id, :completed)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, except: [:new, :create]
  before_action :set_user, only: [:edit, :update, :destroy]
  
  def new
    if logged_in?
      flash[:alert] = "Access denied."
      redirect_to categories_path
    else
      @user = User.new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was updated successfully."
      redirect_to categories_path
    else
      render :edit
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Listed. You have successfully signed up!"
      redirect_to categories_path
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "Account and all associated tasks were succesfully deleted"
    redirect_to root_path
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-5 mb-3 rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Name of Category" %>
          </div>
        </div>
        <br/>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-dark btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-4">
      <%= link_to '[ Cancel and return to categories listing ]', categories_path, class:"text-dark" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category title</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>
<div class="container">
  <div class="card-deck">
    <% @categories.each do |category| %>
        <div class="col-4 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-body">
              <h5 class="card-title"><%= link_to category.title, category_path(category), class: "text-dark" %></h5>
              <p class="card-text"><%= pluralize(category.tasks.count, "task") %></p>
              <%= link_to "View", category_path(category), class: "btn btn-dark" %>
              <%= link_to "Edit", edit_category_path(category), class: "btn btn-dark" %>
              <%= link_to "Delete", category_path(category), class: "btn btn-danger", method: :delete, data: {confirm: "Do you want to proceed in deleting the category?"} %>
            </div>
            <div class="card-footer text-muted">
              <small>Created <%= time_ago_in_words(category.created_at) %> ago,
              edited <%= time_ago_in_words(category.updated_at) %> ago</small>
            </div>
            </div>
          </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Add a category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.title %></h1>
<div class="text-center mt-4">
  <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-outline-dark" %>
  <%= link_to 'Delete', category_path(@category), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Do you want to proceed in deleting the category?"} %>
</div>
<h3 class="text-center mt-4">Tasks</h3>
<%= render 'tasks/task' %>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-secondary alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-light">
  <div id="nav-div">
    <%= link_to "Lis", root_path, class: "navbar-brand", id: "logo" %>
    <span id="nav-span">TED</span>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Add new category", new_category_path, class: "dropdown-item" %>
            <%= link_to "Show all categories", categories_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tasks
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Add new task", new_task_path, class: "dropdown-item" %>
            <%= link_to "Tasks for today", tasks_today_path, class: "dropdown-item" %>
            <%= link_to "Show all tasks", tasks_path, class: "dropdown-item" %>
          </div>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Welcome, #{current_user.email}!", tasks_path, class: "nav-link disabled" %>
          </li>
          <li class="nav-item">
            <%= link_to "Update profile",edit_user_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", logout_path, class: "nav-link", method: :delete %>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign in", login_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LisTED</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-secondary alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @task %>
      <%= form_with(model: @task, class: "shadow p-5 mb-3 rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name of Task" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :detail, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.text_area :detail, rows: 10, class: "form-control shadow rounded", placeholder: "Details of Task" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :due_date, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.date_field :due_date, class: "form-control shadow rounded" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.collection_select(:category_id, current_user.categories, :id, :title,
            {}, { class: "custom-select shadow rounded" }) %> 
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :completed, "Completed?", class: "col-2 col-form-label " %>
          <div class="col-10">
            <%= f.check_box :completed, class: "form-control rounded col-1" %>
          </div>
        </div>

        <br/>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-dark btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-4">
      <%= link_to '[ Cancel and return to tasks listing ]', tasks_path, class:"text-dark" %>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="container">
  <% @tasks.each do |task| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            Due on: <%= task.due_date %> | Status: <%= task.completed ? "Completed" : "Not completed" %>
            <div class="mt-2"><%= link_to task.category.title, category_path(task.category), class: "badge badge-pill badge-secondary" %></div>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to task.name, task_path(task), class: "text-dark" %></h5>
            <p class="card-text"><%= simple_format(truncate(task.detail, length: 150)) %></p>
            <%= link_to "View", task_path(task), class: "btn btn-dark" %>
            <%= link_to "Edit", edit_task_path(task), class: "btn btn-dark" %>
            <%= link_to "Delete", task_path(task), class: "btn btn-danger", method: :delete, data: {confirm: "Do you want to proceed in deleting the task?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(task.created_at) %> ago,
            edited <%= time_ago_in_words(task.updated_at) %> ago</small>
          </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1 class="text-center mt-4">Edit task details</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1 class="text-center mt-4">Listing all tasks</h1>

<%= render 'task' %>

app/views/tasks/new.html.erb
<h1 class="text-center mt-4">Add a task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h2 class="text-center mt-4"><%= @task.name %></h2>

<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          Due on: <%=@task.due_date %> | Status: <%= @task.completed ? "Completed" : "Not completed" %>
          <div class="mt-2"><%= link_to @task.category.title, category_path(@task.category), class: "badge badge-pill badge-secondary" %></div>
        </div>
        <div class="card-body">
          <div class="card-text"><%= simple_format(@task.detail) %></div>
          <%= link_to "Edit", edit_task_path(@task), class: "btn btn-dark" %>
          <%= link_to "Delete", task_path(@task), class: "btn btn-danger", method: :delete, data: {confirm: "Do you want to proceed in deleting the task?"} %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@task.created_at) %> ago,
          edited <%= time_ago_in_words(@task.updated_at) %> ago</small>
        </div>
        </div>
      </div>
  </div>
</div>

app/views/tasks/today.html.erb
<h1 class="text-center mt-4">Tasks due today</h1>
<h6 class="text-center mt-2"><%= "(You have #{@tasks.count} task/s to complete today)" %></h1>
<%= render 'task' %>

app/views/users/_form.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-5 mb-3 rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "juandelacruz@email.com" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label" %>
          <div class="col-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "************" %>
          </div>
        </div>
        <br/>
        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Create account" : "Update account", class: "btn btn-dark btn-lg") %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit user account</h1>
<%= render 'form' %>
<div id="delete-user-container" class="container mt-4">
  <h1 class="text-center mb-4 ">Danger Zone</h1> 
  <div class="row justify-content-center shadow p-5 mb-3 rounded">
    <%= link_to 'Delete my account', user_path(current_user), class: "btn btn-danger btn-lg", method: :delete, data: {confirm: "Do you want to proceed in deleting your account?"} %>
  </div>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Listed</h1>
<%= render 'form' %>